#!/bin/sh

echo "Starting rcS..."

mkdir -p /lib/modules/`uname -r`

echo "++ Mounting filesystem"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

echo "++ Setting up mdev"
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mount -t debugfs none /sys/kernel/debug/

# the device driver is not creating this node, so for now
# create the devcfg device node manually
mkdir -p /dev/pts
mkdir -p /dev/i2c
mount -t devpts devpts /dev/pts
mount -a

mkdir -p /etc/network/if-pre-up.d
#mkdir -p /var/run

ifconfig lo 127.0.0.1 up
ifplugd -I
#ifdown -a -i /mnt/mmc-disk3/interfaces
#ifup -a -i /mnt/mmc-disk3/interfaces &

echo "++ Starting telnet daemon"
#telnetd -l /bin/sh

echo "++ Starting http daemon"
#httpd -h /var/www

echo "++ Starting ftp daemon"
#tcpsvd 0:21 ftpd ftpd -w /&

echo "++ Starting ssh daemon"
if [ -e /usr/sbin/sshd ]; then                                                                                                                                                                 
	/usr/sbin/sshd
else                                                                                                                                                                                           
	dropbear
fi

echo "rcS Complete"
